### ISSUE TITLE
WooCommerce 2.6.x 

### ISSUE THREAD

**Issue by Kostaefe** [vyskoczilova/woocommerce-payforpayment-old#39]
After reseting shipping in WooCommerce 2.6.x The old free shipping is not exist any more. 
But a new one. https://www.woothemes.com/2016/06/woocommerce-26-zipping-zebra/

On COD (Cash on delivery) i use the (Don’t charge this fee when free shipping is available.) But maybe your Plugin don't find the new free shipping method from WooCommerce 2.6.x. ...and charge it....

did you have any solution? Maybe on the next update?

**Comment by laszlo69** [comment]
Have the same problem.
When come the next update?

**Comment by oblaum** [comment]
update would be great. a paid version would be okay for me!

**Comment by vyskoczilova** [comment]
Fixed in the upcoming update 2.0.1.
